networks:
  backend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"

volumes:
  bingo_db:

services:
  bingo_db:
    container_name: bingo_db
    networks:
      - backend
    image: cr.yandex/crpgs3g59it0ouonuleo/bingo:db
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - 5432:5432
    volumes:
      - bingo_db:/var/lib/postgresql/data
      - ./postgres/config:/docker-entrypoint-initdb.d/
    

  bingo_init:
    container_name: bingo_init
    networks:
      - backend
    image: cr.yandex/crpgs3g59it0ouonuleo/bingo:init
    depends_on:
      - bingo_db
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_HOST: bingo_db
      POSTGRES_PORT: 5432
    