version: '3.7'
services:
  bingo:
    container_name: bingo
    image: "cr.yandex/crps6iajan0jje7v30hd/bingo:myapp"
    restart: always
    network_mode: "host"
  unifiedagent:
    container_name: unifiedagent
    image: "cr.yandex/yc/unified-agent"
    environment:
      FOLDER_ID: "${folder_id}"
    restart: always
    network_mode: "host"
    volumes:
      - /ua:/etc/yandex/unified_agent/conf.d