
services:
  bingo_app:
    container_name: bingo_app
    image: cr.yandex/${registry_id}/bingo:app
    ports:
      - 8000:32531
    labels:
      - "autoheal=true"
    networks:
      - bingo_app
    healthcheck:
      test: curl --fail -s http://127.0.0.1:32531/api/movie || exit 1
      interval: 1s
      timeout: 1s
      retries: 2
      start_period: 30s
    restart: on-failure
  
  autoheal:
    image: willfarrell/autoheal
    container_name: autoheal
    restart: always
    environment:
      AUTOHEAL_CONTAINER_LABEL: "autoheal"
      AUTOHEAL_INTERVAL: "5"
    networks:
      - bingo_app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  bingo_app:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 10.25.0.0/24